# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    app.mailer.transport:  smtp 
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.mailer:
            class:        AppBundle\Mailer
            arguments:    ['%app.mailer.transport%']
    app.db_calendar:
            class:        AppBundle\Utils\CalendarBdActions
    app.beta.html:
            class:        AppBundle\Beta\BetaHtml  
    app.beta.listener:
            class:        AppBundle\Beta\BetaListener
            arguments:    ['@app.beta.html', "2013-10-20"]
            tags:
                    - { name: kernel.event_listener, event: kernel.response, method: processBeta }