<?php

namespace AppBundle\Repository\Lucky;

/**
 * CalendarDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarDayRepository extends \Doctrine\ORM\EntityRepository
{
}
