<?php

namespace AppBundle\Repository\Lucky;

use AppBundle\Entity\Lucky\CalendarDay;



/**
 * CalendarDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarDayRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function upsert_to_db($data)
    {
        $var=$data;
        foreach ($data as $key => $value){
            $day= $key;
            $mood = $value;
            
            $em = $this->getEntityManager();
            //$em->getRepository('AppBundle\Entity\Lucky\CalendarDay')->findBy(array('day' => '2013-12-24'));
            $em->getRepository('AppBundle:Product')
                 ->find(1);
            //  $product = $this->getDoctrine()
            //     ->getRepository(Product::class)
            //     ->find(1);
            // $day_found = $this->getDoctrine()->getRepository('Lucky:CalendarDayRepository')
            // ->findBy(array('day' => $day));
            // $tenUsers = $em->getRepository('MyProject\Domain\User')->findBy(array('age' => 20), array('name' => 'ASC'), 10, 0);
            $this->create_day($day,$mood);
            
            
            
    
    }

    }//end upsert
    
    public function create_day($date2,$mood)
    {
        $cal_day = new CalendarDay();
        $cal_day->setUser(1);
        $date =  new \DateTime("now");
        $cal_day->setDay($date);
        $cal_day->setMood(1);
      
        $em = $this->getEntityManager();
        $em->persist($cal_day);
        $em->flush();
    }
    
    
}
